{% set data = load_setup_py_data() %}

package:
  name: "darts"
  version: "0.9.1"

source:
  # root folder, not the package
  path: "../../../darts"

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv'
  noarch: python

requirements:
  host:
    - python
  run:
    - python
  {% for req in data.get('install_requires', []) %}
    # torch is called pytorch in anaconda
    - {{ req | replace("torch", "pytorch")}}
  {% endfor %}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: APACHE
  license_file: LICENSE
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - {{ data.get('author') }}
