{% set pyproject = load_file_data('../../pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}

package:
  name: {{ project.get('name', 'darts') }}
  version: {{ project.get('version', '0.40.0') }}

source:
  # root folder, not the package
  path: "../../../darts"

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv'

requirements:
  host:
    - python {{ project.get('requires-python', '>=3.10') }}
    - pip
    - setuptools >=57
    - wheel
  run:
    - python {{ project.get('requires-python', '>=3.10') }}
  {% for req in project.get('dependencies', []) %}
    - {{ req }}
  {% endfor %}

about:
  home: {{ project.get('urls', {}).get('Homepage', 'https://unit8co.github.io/darts/') }}
  license: {{ project.get('license', 'Apache-2.0') }}
  license_family: APACHE
  license_file: LICENSE
  summary: {{ project.get('description', 'A python library for easy manipulation and forecasting of time series.') }}

extra:
  recipe-maintainers:
    {% for maintainer in project.get('maintainers', []) %}
    - {{ maintainer.get('name', 'Unit8 SA') }}
    {% endfor %}
