{% set data = load_setup_py_data() %}

package:
  name: "u8timeseries"
  version: {{ data.get('version').split('-', 1)[0] }}

source:
  # root folder, not the package
  path: "../../../u8timeseries"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6,<3.8
  run:
  # only essential requirements to use this library ~ setup.py install_requires ~ requirements/main.txt
    - python >=3.6,<3.8
    - numpy >=1.18.1
    - scipy >=1.4.1
    - statsmodels >=0.11.1
    - pmdarima >=1.5.3
    - matplotlib >=3.2.1
    - fbprophet >=0.5
    - pandas >=0.23.1
    - tqdm >=4.32.1

test:
  imports:
    - u8timeseries

about:
  home: "http://github.com/unit8co/u8timeseries"
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A collection of easy-to-use timeseries forecasting models"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    # TODO
    - your-github-id-here
