{% set data = load_setup_py_data() %}

package:
  name: "u8timeseries"
  version: {{ data.get('version').split('-', 1)[0] }}

source:
  # root folder, not the package
  path: "../../../u8timeseries"

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv'

requirements:
  host:
    - python >=3.6
  run:
  # only essential requirements to use this library ~ setup.py install_requires ~ requirements/main.txt
    - python >=3.6
    - numpy >=1.18.1
    - scipy >=1.4.1
    - statsmodels >=0.11.1
    - matplotlib >=3.2.1
    - fbprophet >=0.5
    - pandas >=0.23.1
    - tqdm >=4.32.1
    - ipywidgets
    - plotly >=4.6.0
    - pmdarima >=1.5.3 # note that it exists in the anaconda repo but is not supported so reinstall it through pip

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: APACHE
  license_file: LICENSE
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - {{ data.get('author') }}
