{% set name = "u8timeseries" %}
{% set version = "0.0.2" %}
# TODO: version above needs to injected like in setup.py

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # root folder, not the package
  path: "../../../u8timeseries"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
  run:
    - python
    - numpy >=1.18.1
    - scipy >=1.4.1
    - statsmodels >=0.11.1
    - pmdarima >=1.5.3
    - matplotlib >=3.2.1
    - fbprophet >=0.5
    - pandas >=0.23.1
    - tqdm >=4.32.1

# test:
  # here could add imports and tests execution; note that imports seems to be buggy

about:
  home: "http://github.com/unit8co/u8timeseries"
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A collection of easy-to-use timeseries forecasting models"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    # TODO
    - your-github-id-here
