name: ci_workflow

on:
  push:
    branches:
      - github_action_CI
      - master


jobs:

  run_tests:

    runs-on: ubuntu-latest

    steps:
    - run: ls
    - name: Build docker step
      run: ./build_docker.sh

    - name: Run docker step
      run: ./run_test_docker.sh
